=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/Integration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Integration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Steps">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="IOInput" type="IOType" />
              <xs:element name="IOOutput" type="IOType" />
              <xs:element name="Map" type="MapType" />
              <xs:element name="Filter" type="WorksheetStepType" />
              <xs:element name="Reduce" type="ReduceType" />
              <xs:element name="Switch" type="SwitchType" />
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="IOType">
    <xs:attribute name="Id" type="xs:string" use="required" />
    <xs:attribute name="Kind" type="xs:string" use="required" />
    <xs:attribute name="FilePath" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="MapType">
    <xs:sequence>
      <xs:element name="Worksheet" type="WorksheetType" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="WorksheetStepType">
    <xs:sequence>
      <xs:element name="Worksheet" type="WorksheetType" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="ReduceType">
    <xs:sequence>
      <xs:element name="InitialStateJson" type="xs:string" />
      <xs:element name="Worksheet" type="WorksheetType" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" use="required" />
    <xs:attribute name="OutputField" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="SwitchType">
    <xs:sequence>
      <xs:element name="Worksheet" type="WorksheetType" />
      <xs:element name="Branch" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Map" type="MapType" />
          </xs:sequence>
          <xs:attribute name="WorkCell" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="WorksheetType">
    <xs:choice>
      <xs:sequence>
        <xs:element name="Name" type="xs:string" minOccurs="0" />
        <xs:element name="Variables" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Variable" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Key" type="xs:string" />
                    <xs:element name="Value" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Cells">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="WorkCell" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Id" type="xs:string" />
                    <xs:element name="Name" type="xs:string" />
                    <xs:element name="Formula" type="xs:string" />
                    <xs:element name="Comments" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:choice>
    <xs:attribute name="FilePath" type="xs:string" />
  </xs:complexType>

</xs:schema>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/from-csharp-tests/TestIntegrationWithFileReferences.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/Integration.xsd" Name="Sales total">
    <Steps>
        <CsvInput Id="input" FilePath="__INPUT_PATH__"/>
        <Map Id="map">
            <Worksheet FilePath="Map.xml"/>
        </Map>
        <Filter Id="filter">
            <Worksheet FilePath="Filter.xml"/>
        </Filter>
        <Reduce Id="reduce" OutputField="Total">
            <InitialStateJson>0</InitialStateJson>
            <Worksheet FilePath="Reduce.xml"/>
        </Reduce>
        <CsvOutput Id="output" FilePath="__OUTPUT_PATH__"/>
    </Steps>
</Integration>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/TestIntegration.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/Integration.xsd" Name="Sales total">
    <Steps>
        <IOInput Id="input" Kind="CSVReader" FilePath="Input1.csv"/>
        <Map Id="map">
            <Worksheet>
                <Name>Map</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Name</Name>
                        <Formula>InputRecord.Name</Formula>
                        <Comments/>
                    </WorkCell>
                    <WorkCell>
                        <Id>2</Id>
                        <Name>Amount</Name>
                        <Formula>Value(InputRecord.Amount)</Formula>
                        <Comments/>
                    </WorkCell>
                    <WorkCell>
                        <Id>3</Id>
                        <Name>IsActive</Name>
                        <Formula>InputRecord.Active = &quot;true&quot;</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Map>
        <Filter Id="filter">
            <Worksheet>
                <Name>Filter</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Keep</Name>
                        <Formula>InputRecord.IsActive = &quot;false&quot;</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Filter>
        <Reduce Id="reduce" OutputField="Total">
            <InitialStateJson>0</InitialStateJson>
            <Worksheet>
                <Name>Reduce</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Total</Name>
                        <Formula>State + InputRecord.Amount</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Reduce>
        <IOOutput Id="output" Kind="CSVWriter" FilePath="Output1.csv"/>
    </Steps>
</Integration>
