=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/Integration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Integration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Steps">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="IOInput" type="IOType" />
              <xs:element name="IOOutput" type="IOType" />
              <xs:element name="Map" type="MapType" />
              <xs:element name="Filter" type="WorksheetStepType" />
              <xs:element name="Reduce" type="ReduceType" />
              <xs:element name="Switch" type="SwitchType" />
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="IOType">
    <xs:attribute name="Id" type="xs:string" use="required" />
    <xs:attribute name="Kind" type="xs:string" use="required" />
    <xs:attribute name="FilePath" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="MapType">
    <xs:sequence>
      <xs:element name="Worksheet" type="WorksheetType" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="WorksheetStepType">
    <xs:sequence>
      <xs:element name="Worksheet" type="WorksheetType" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="ReduceType">
    <xs:sequence>
      <xs:element name="InitialStateJson" type="xs:string" />
      <xs:element name="Worksheet" type="WorksheetType" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" use="required" />
    <xs:attribute name="OutputField" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="SwitchType">
    <xs:sequence>
      <xs:element name="Worksheet" type="WorksheetType" />
      <xs:element name="Branch" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Map" type="MapType" />
          </xs:sequence>
          <xs:attribute name="WorkCell" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="WorksheetType">
    <xs:choice>
      <xs:sequence>
        <xs:element name="Name" type="xs:string" minOccurs="0" />
        <xs:element name="Variables" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Variable" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Key" type="xs:string" />
                    <xs:element name="Value" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Cells">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="WorkCell" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Id" type="xs:string" />
                    <xs:element name="Name" type="xs:string" />
                    <xs:element name="Formula" type="xs:string" />
                    <xs:element name="Comments" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:choice>
    <xs:attribute name="FilePath" type="xs:string" />
  </xs:complexType>

</xs:schema>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/from-csharp-tests/MockDeferredOutput.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/Integration.xsd" Name="Mock Deferred Output Test">
    <Steps>
        <SqlInput Id="input1" ConnectionString="Server=invalid;">
            <MockCsv>
Name,Amount
Alice,10
Bob,20
            </MockCsv>
        </SqlInput>
        <Reduce Id="reduce1" OutputField="Sum">
            <InitialStateJson>0</InitialStateJson>
            <Worksheet>
                <Name>Reduce</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Sum</Name>
                        <Formula>State + Value(InputRecord.Amount)</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Reduce>
        <CsvOutput Id="output1" FilePath="__OUTPUT_PATH__" />
    </Steps>
</Integration>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/from-csharp-tests/MockCsvInline.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/Integration.xsd" Name="Mock Data Inline Test">
    <Steps>
        <SqlInput Id="input1" ConnectionString="Server=invalid;Database=none;">
            <MockCsv>
Name,Active,Amount
Alice,true,10
Bob,false,100
Cara,true,5
            </MockCsv>
        </SqlInput>
        <Map Id="map">
            <Worksheet>
                <Name>Map</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Total</Name>
                        <Formula>Value(InputRecord.Amount) * 2</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Map>
    </Steps>
</Integration>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/TestIntegrationWithFileReferences.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/Integration.xsd" Name="Sales total">
    <Steps>
        <IOInput Id="input" Kind="CSVReader" FilePath="Input1.csv"/>
        <Map Id="map">
            <Worksheet FilePath="Map.xml"/>
        </Map>
        <Filter Id="filter">
            <Worksheet FilePath="Filter.xml"/>
        </Filter>
        <Reduce Id="reduce" OutputField="Total">
            <InitialStateJson>0</InitialStateJson>
            <Worksheet FilePath="Reduce.xml"/>
        </Reduce>
        <IOOutput Id="output" Kind="CSVWriter" FilePath="Output1.csv"/>
        
    </Steps>
</Integration>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/from-csharp-tests/Switch.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/Integration.xsd" Name="Switch branches">
    <Steps>
        <CsvInput Id="input" FilePath="__INPUT_PATH__" />
<!--        <Map Id="map">-->
<!--            <Worksheet FilePath="Map.xml"/>-->
<!--        </Map>-->
        <!-- issue, switch is not working well, it is not executing per input row and not yielding final results. Actually NO
          the integration is not supposed to yield results unless sent to IO writer -->
        <Switch Id="choose">
            <Worksheet>
                <Name>Chooser Sheet</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>IsActive</Name>
<!--                        <Formula>InputRecord.IsActive</Formula>-->
                        <Formula>InputRecord.Active</Formula>
                    </WorkCell>
                    <WorkCell>
                        <Id>2</Id>
                        <Name>IsInactive</Name>
                        <Formula>Not(Active)</Formula>
<!--                        <Formula>Not(IsActive)</Formula>-->
                    </WorkCell>
                </Cells>
            </Worksheet>
            <Branch WorkCell="IsActive">
                <Map Id="yes">
                    <Worksheet>
                        <Cells>
                            <WorkCell>
                                <Id>1</Id>
                                <Name>Result</Name>
                                <Formula>InputRecord.Name &amp; &quot;-yes&quot;</Formula>
                            </WorkCell>
                        </Cells>
                    </Worksheet>
                </Map>
            </Branch>
            <Branch WorkCell="IsInactive">
                <Map Id="no">
                    <Worksheet>
                        <Cells>
                            <WorkCell>
                                <Id>1</Id>
                                <Name>Result</Name>
                                <Formula>InputRecord.Name &amp; &quot;-no&quot;</Formula>
                            </WorkCell>
                        </Cells>
                    </Worksheet>
                </Map>
            </Branch>
        </Switch>
    </Steps>
</Integration>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/from-csharp-tests/TestIntegration.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/Integration.xsd" Name="Sales total">
    <Steps>
        <CsvInput Id="input" FilePath="__INPUT_PATH__"/>
        <Map Id="map">
            <Worksheet>
                <Name>Map</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Name</Name>
                        <Formula>InputRecord.Name</Formula>
                        <Comments/>
                    </WorkCell>
                    <WorkCell>
                        <Id>2</Id>
                        <Name>Amount</Name>
                        <Formula>Value(InputRecord.Amount)</Formula>
                        <Comments/>
                    </WorkCell>
                    <WorkCell>
                        <Id>3</Id>
                        <Name>IsActive</Name>
                        <Formula>InputRecord.Active = &quot;true&quot;</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Map>
        <Filter Id="filter">
            <Worksheet>
                <Name>Filter</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Keep</Name>
                        <Formula>InputRecord.IsActive</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Filter>
        <Reduce Id="reduce" OutputField="Total">
            <InitialStateJson>0</InitialStateJson>
            <Worksheet>
                <Name>Reduce</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Total</Name>
                        <Formula>State + InputRecord.Amount</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Reduce>
        <CsvOutput Id="output" FilePath="__OUTPUT_PATH__"/>
    </Steps>
</Integration>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/from-csharp-tests/CliMockData.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/Integration.xsd" Name="CLI Mock Test">
    <Steps>
        <SqlInput Id="sqlInput" ConnectionString="Server=invalid;">
            <MockCsv>
Name,Active,Amount
Alice,true,10
Cara,true,5
            </MockCsv>
        </SqlInput>
        <Map Id="map">
            <Worksheet>
                <Name>Map</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Name</Name>
                        <Formula>InputRecord.Name</Formula>
                        <Comments/>
                    </WorkCell>
                    <WorkCell>
                        <Id>2</Id>
                        <Name>Amount</Name>
                        <Formula>Value(InputRecord.Amount)</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Map>
        <CsvOutput Id="output" FilePath="__OUTPUT_PATH__" />
    </Steps>
</Integration>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/Switch.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/Integration.xsd" Name="Switch branches">
    <Steps>
        <IOInput Id="input" Kind="CSVReader" FilePath="Input1.csv" />
        <Switch Id="choose">
            <Worksheet>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>IsActive</Name>
                        <Formula>InputRecord.Active = &quot;true&quot;</Formula>
                    </WorkCell>
                    <WorkCell>
                        <Id>2</Id>
                        <Name>IsInactive</Name>
                        <Formula>Not IsActive</Formula>
                    </WorkCell>
                </Cells>
            </Worksheet>
            <Branch WorkCell="IsActive">
                <Map Id="yes">
                    <Worksheet>
                        <Cells>
                            <WorkCell>
                                <Id>1</Id>
                                <Name>Result</Name>
                                <Formula>InputRecord.Name &amp; &quot;-yes&quot;</Formula>
                            </WorkCell>
                        </Cells>
                    </Worksheet>
                </Map>
            </Branch>
            <Branch WorkCell="IsInactive">
                <Map Id="no">
                    <Worksheet>
                        <Cells>
                            <WorkCell>
                                <Id>1</Id>
                                <Name>Result</Name>
                                <Formula>InputRecord.Name &amp; &quot;-no&quot;</Formula>
                            </WorkCell>
                        </Cells>
                    </Worksheet>
                </Map>
            </Branch>
        </Switch>
    </Steps>
</Integration>

=== TheJuanitoLearnsShow/PuppyWorkbooks.VSCode/src/sample/Integration/from-csharp-tests/MockCsvFilePath.xml
<?xml version="1.0" encoding="utf-8"?>
<Integration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/Integration.xsd" Name="Mock Data File Test">
    <Steps>
        <SqlInput Id="sqlInput" ConnectionString="Server=invalid;" MockCsvFilePath="__MOCK_CSV_PATH__" />
        <Map Id="map">
            <Worksheet>
                <Name>Map</Name>
                <Cells>
                    <WorkCell>
                        <Id>1</Id>
                        <Name>Greeting</Name>
                        <Formula>"Hello " &amp; InputRecord.Name</Formula>
                        <Comments/>
                    </WorkCell>
                </Cells>
            </Worksheet>
        </Map>
    </Steps>
</Integration>
